// <auto-generated />
using System;
using MarketAnalysis.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketAnalysis.Infrastructure.Migrations
{
    [DbContext(typeof(MarketAnalysisDbContext))]
    [Migration("20260210145441_AddUseMlScoringToUserScanConfig")]
    partial class AddUseMlScoringToUserScanConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketAnalysis.Core.Entities.FundamentalSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Beta")
                        .HasColumnType("double precision");

                    b.Property<double>("CompositeScore")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double?>("DebtToEquity")
                        .HasColumnType("double precision");

                    b.Property<double?>("DividendYield")
                        .HasColumnType("double precision");

                    b.Property<double?>("EarningsPerShare")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("FiftyTwoWeekHigh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("FiftyTwoWeekLow")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double?>("ForwardPe")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("FreeCashFlow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("GrowthScore")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("OperatingMargin")
                        .HasColumnType("double precision");

                    b.Property<double?>("PeRatio")
                        .HasColumnType("double precision");

                    b.Property<double?>("PegRatio")
                        .HasColumnType("double precision");

                    b.Property<double?>("PriceToBook")
                        .HasColumnType("double precision");

                    b.Property<double?>("ProfitMargin")
                        .HasColumnType("double precision");

                    b.Property<double>("QualityScore")
                        .HasColumnType("double precision");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RecommendationKey")
                        .HasColumnType("text");

                    b.Property<double?>("ReturnOnEquity")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("RevenuePerShare")
                        .HasColumnType("double precision");

                    b.Property<double>("SafetyScore")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TargetMeanPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("ValueScore")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "SnapshotDate");

                    b.ToTable("FundamentalSnapshots");
                });

            modelBuilder.Entity("MarketAnalysis.Core.Entities.IndexDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastRefreshedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string[]>("Tickers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("IndexDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsEnabled = false,
                            LastRefreshedUtc = new DateTime(2026, 2, 10, 14, 54, 39, 988, DateTimeKind.Utc).AddTicks(430),
                            Name = "S&P 500",
                            Tickers = new string[0]
                        },
                        new
                        {
                            Id = 2,
                            IsEnabled = false,
                            LastRefreshedUtc = new DateTime(2026, 2, 10, 14, 54, 39, 988, DateTimeKind.Utc).AddTicks(432),
                            Name = "NASDAQ 100",
                            Tickers = new string[0]
                        });
                });

            modelBuilder.Entity("MarketAnalysis.Core.Entities.PriceHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AdjClose")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("StockId", "Date")
                        .IsUnique();

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("MarketAnalysis.Core.Entities.ScanReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConfigSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStocksScanned")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReportDate", "Category");

                    b.ToTable("ScanReports");
                });

            modelBuilder.Entity("MarketAnalysis.Core.Entities.ScanReportEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("CompositeScore")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Direction")
                        .HasColumnType("text");

                    b.Property<double>("FundamentalScore")
                        .HasColumnType("double precision");

                    b.Property<string>("PatternDetected")
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ScanReportId")
                        .HasColumnType("integer");

                    b.Property<double>("SentimentScore")
                        .HasColumnType("double precision");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<double>("TechnicalScore")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ScanReportId");

                    b.HasIndex("StockId");

                    b.ToTable("ScanReportEntries");
                });

            modelBuilder.Entity("MarketAnalysis.Core.Entities.SentimentScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AnalysisDate")
                        .HasColumnType("date");

                    b.Property<string>("Headlines")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("NegativeScore")
                        .HasColumnType("double precision");

                    b.Property<double>("NeutralScore")
                        .HasColumnType("double precision");

                    b.Property<double>("PositiveScore")
                        .HasColumnType("double precision");

                    b.Property<int>("SampleSize")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "AnalysisDate", "Source");

                    b.ToTable("SentimentScores");
                });

            modelBuilder.Entity("MarketAnalysis.Core.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Exchange")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("MarketAnalysis.Core.Entities.TechnicalSignal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("DetectedDate")
                        .HasColumnType("date");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("KeyPriceLevels")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("PatternType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "DetectedDate");

                    b.ToTable("TechnicalSignals");
                });

            modelBuilder.Entity("MarketAnalysis.Core.Entities.UserScanConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string[]>("EnabledCategories")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string[]>("EnabledIndicators")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string[]>("EnabledPatterns")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string[]>("EnabledSentimentSources")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<double>("FundamentalWeight")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<double?>("MaxDebtToEquity")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxPERatio")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("MinMarketCap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("MinProfitMargin")
                        .HasColumnType("double precision");

                    b.Property<int>("MinSentimentSampleSize")
                        .HasColumnType("integer");

                    b.Property<double?>("MinSentimentScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("PriceRangeMax")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PriceRangeMin")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("SentimentWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("TechnicalWeight")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseMlScoring")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("UserScanConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 2, 10, 14, 54, 39, 987, DateTimeKind.Utc).AddTicks(9908),
                            EnabledCategories = new[] { "DayTrade", "SwingTrade", "ShortTermHold", "LongTermHold" },
                            EnabledIndicators = new[] { "RSI14", "MACD", "SMA50", "SMA200", "BollingerBands", "ATR", "OBV" },
                            EnabledPatterns = new[] { "DoubleTop", "DoubleBottom", "HeadAndShoulders", "InverseHeadAndShoulders", "BullFlag", "BearFlag", "AscendingTriangle", "DescendingTriangle", "SymmetricalTriangle", "RisingWedge", "FallingWedge", "Pennant", "CupAndHandle" },
                            EnabledSentimentSources = new[] { "News", "Reddit", "StockTwits" },
                            FundamentalWeight = 0.34999999999999998,
                            IsDefault = true,
                            MaxDebtToEquity = 200.0,
                            MaxPERatio = 50.0,
                            MinProfitMargin = 0.050000000000000003,
                            MinSentimentSampleSize = 3,
                            Name = "Default",
                            PriceRangeMax = 500m,
                            PriceRangeMin = 5m,
                            SentimentWeight = 0.25,
                            TechnicalWeight = 0.40000000000000002,
                            UpdatedAtUtc = new DateTime(2026, 2, 10, 14, 54, 39, 987, DateTimeKind.Utc).AddTicks(9911),
                            UseMlScoring = false
                        });
                });

            modelBuilder.Entity("MarketAnalysis.Core.Entities.WatchList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("WatchLists");
                });

            modelBuilder.Entity("MarketAnalysis.Core.Entities.WatchListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<int>("WatchListId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.HasIndex("WatchListId", "StockId")
                        .IsUnique();

                    b.ToTable("WatchListItems");
                });

            modelBuilder.Entity("MarketAnalysis.Core.Entities.FundamentalSnapshot", b =>
                {
                    b.HasOne("MarketAnalysis.Core.Entities.Stock", "Stock")
                        .WithMany("FundamentalSnapshots")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("MarketAnalysis.Core.Entities.PriceHistory", b =>
                {
                    b.HasOne("MarketAnalysis.Core.Entities.Stock", "Stock")
                        .WithMany("PriceHistories")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("MarketAnalysis.Core.Entities.ScanReportEntry", b =>
                {
                    b.HasOne("MarketAnalysis.Core.Entities.ScanReport", "ScanReport")
                        .WithMany("Entries")
                        .HasForeignKey("ScanReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketAnalysis.Core.Entities.Stock", "Stock")
                        .WithMany("ScanReportEntries")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanReport");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("MarketAnalysis.Core.Entities.SentimentScore", b =>
                {
                    b.HasOne("MarketAnalysis.Core.Entities.Stock", "Stock")
                        .WithMany("SentimentScores")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("MarketAnalysis.Core.Entities.TechnicalSignal", b =>
                {
                    b.HasOne("MarketAnalysis.Core.Entities.Stock", "Stock")
                        .WithMany("TechnicalSignals")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("MarketAnalysis.Core.Entities.WatchListItem", b =>
                {
                    b.HasOne("MarketAnalysis.Core.Entities.Stock", "Stock")
                        .WithMany("WatchListItems")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketAnalysis.Core.Entities.WatchList", "WatchList")
                        .WithMany("Items")
                        .HasForeignKey("WatchListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");

                    b.Navigation("WatchList");
                });

            modelBuilder.Entity("MarketAnalysis.Core.Entities.ScanReport", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("MarketAnalysis.Core.Entities.Stock", b =>
                {
                    b.Navigation("FundamentalSnapshots");

                    b.Navigation("PriceHistories");

                    b.Navigation("ScanReportEntries");

                    b.Navigation("SentimentScores");

                    b.Navigation("TechnicalSignals");

                    b.Navigation("WatchListItems");
                });

            modelBuilder.Entity("MarketAnalysis.Core.Entities.WatchList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
