using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketAnalysis.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddAiPrediction : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "AiPredictions",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    StockId = table.Column<int>(type: "integer", nullable: false),
                    PredictionDate = table.Column<DateOnly>(type: "date", nullable: false),
                    ModelUsed = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    Summary = table.Column<string>(type: "text", nullable: false),
                    Outlook = table.Column<string>(type: "text", nullable: false),
                    Recommendation = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    Confidence = table.Column<double>(type: "double precision", nullable: false),
                    KeyFactorsJson = table.Column<string>(type: "jsonb", nullable: false),
                    RiskFactorsJson = table.Column<string>(type: "jsonb", nullable: false),
                    EntryPrice = table.Column<decimal>(type: "numeric(18,4)", nullable: false),
                    StopLoss = table.Column<decimal>(type: "numeric(18,4)", nullable: false),
                    ProfitTarget = table.Column<decimal>(type: "numeric(18,4)", nullable: false),
                    ExitPrice = table.Column<decimal>(type: "numeric(18,4)", nullable: false),
                    TradeRationale = table.Column<string>(type: "text", nullable: false),
                    PredictedDirection = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    ActualPriceAt5Days = table.Column<decimal>(type: "numeric(18,4)", nullable: true),
                    ActualPriceAt10Days = table.Column<decimal>(type: "numeric(18,4)", nullable: true),
                    ActualPriceAt30Days = table.Column<decimal>(type: "numeric(18,4)", nullable: true),
                    OutcomeAt5Days = table.Column<string>(type: "text", nullable: true),
                    OutcomeAt10Days = table.Column<string>(type: "text", nullable: true),
                    OutcomeAt30Days = table.Column<string>(type: "text", nullable: true),
                    EvaluatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    IsAutoGenerated = table.Column<bool>(type: "boolean", nullable: false),
                    CreatedAtUtc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AiPredictions", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AiPredictions_Stocks_StockId",
                        column: x => x.StockId,
                        principalTable: "Stocks",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.UpdateData(
                table: "IndexDefinitions",
                keyColumn: "Id",
                keyValue: 1,
                column: "LastRefreshedUtc",
                value: new DateTime(2026, 4, 16, 17, 37, 18, 870, DateTimeKind.Utc).AddTicks(3875));

            migrationBuilder.UpdateData(
                table: "IndexDefinitions",
                keyColumn: "Id",
                keyValue: 2,
                column: "LastRefreshedUtc",
                value: new DateTime(2026, 4, 16, 17, 37, 18, 870, DateTimeKind.Utc).AddTicks(3877));

            migrationBuilder.UpdateData(
                table: "UserScanConfigs",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAtUtc", "UpdatedAtUtc" },
                values: new object[] { new DateTime(2026, 4, 16, 17, 37, 18, 870, DateTimeKind.Utc).AddTicks(3695), new DateTime(2026, 4, 16, 17, 37, 18, 870, DateTimeKind.Utc).AddTicks(3697) });

            migrationBuilder.CreateIndex(
                name: "IX_AiPredictions_EvaluatedAt",
                table: "AiPredictions",
                column: "EvaluatedAt");

            migrationBuilder.CreateIndex(
                name: "IX_AiPredictions_PredictionDate",
                table: "AiPredictions",
                column: "PredictionDate");

            migrationBuilder.CreateIndex(
                name: "IX_AiPredictions_StockId_PredictionDate",
                table: "AiPredictions",
                columns: new[] { "StockId", "PredictionDate" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AiPredictions");

            migrationBuilder.UpdateData(
                table: "IndexDefinitions",
                keyColumn: "Id",
                keyValue: 1,
                column: "LastRefreshedUtc",
                value: new DateTime(2026, 4, 9, 13, 21, 56, 747, DateTimeKind.Utc).AddTicks(5750));

            migrationBuilder.UpdateData(
                table: "IndexDefinitions",
                keyColumn: "Id",
                keyValue: 2,
                column: "LastRefreshedUtc",
                value: new DateTime(2026, 4, 9, 13, 21, 56, 747, DateTimeKind.Utc).AddTicks(5752));

            migrationBuilder.UpdateData(
                table: "UserScanConfigs",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAtUtc", "UpdatedAtUtc" },
                values: new object[] { new DateTime(2026, 4, 9, 13, 21, 56, 747, DateTimeKind.Utc).AddTicks(5432), new DateTime(2026, 4, 9, 13, 21, 56, 747, DateTimeKind.Utc).AddTicks(5434) });
        }
    }
}
