namespace MarketAnalysis.Core.Entities;

public class AiPrediction
{
    public long Id { get; set; }

    public int StockId { get; set; }
    public Stock Stock { get; set; } = null!;

    public DateOnly PredictionDate { get; set; }
    public string ModelUsed { get; set; } = "";

    public string Summary { get; set; } = "";
    public string Outlook { get; set; } = "";
    public string Recommendation { get; set; } = "";
    public double Confidence { get; set; }

    public string KeyFactorsJson { get; set; } = "[]";
    public string RiskFactorsJson { get; set; } = "[]";

    public decimal EntryPrice { get; set; }
    public decimal StopLoss { get; set; }
    public decimal ProfitTarget { get; set; }
    public decimal ExitPrice { get; set; }
    public string TradeRationale { get; set; } = "";

    public string PredictedDirection { get; set; } = "";

    public decimal? ActualPriceAt5Days { get; set; }
    public decimal? ActualPriceAt10Days { get; set; }
    public decimal? ActualPriceAt30Days { get; set; }

    public string? OutcomeAt5Days { get; set; }
    public string? OutcomeAt10Days { get; set; }
    public string? OutcomeAt30Days { get; set; }

    public DateTime? EvaluatedAt { get; set; }
    public bool IsAutoGenerated { get; set; }

    public DateTime CreatedAtUtc { get; set; }
}
